### ISSUE TITLE
1.1 Pre-release build 1180 - Unsupported KSP version - please use 1.0.5

### ISSUE THREAD

**Issue by NWRogue** [JPLRepo/TarsierSpaceTechnology#23]
Just downloaded the latest TST build and the latest KSP 1.1 build and got that message on startup.

x64 version on Windows 10.

I can see the parts in the VAB though.

**Comment by NWRogue** [comment]
Looks to be the AVC version file, still points to 1.0.5 as the supported version.

**Comment by JPLRepo** [comment]
AVC has not been updated and won't be until full release of 1.1 and 6.0 of TST.

**Comment by JPLRepo** [comment]
Closing. Full release now out.
