### ISSUE TITLE
Hard drive science fill should only pull from experiments.

### ISSUE THREAD

**Issue by sentania** [JPLRepo/TarsierSpaceTechnology#38]
When you fill a hard drive it should only pull from experiments and not from other science containers, i.e. crew modules.

Hard drives are useful with the recent changes to the MPL because it allows you to easily store multiple copies of an experiement, but by pulling from a crew container it can make it difficult to keep track of what you have where and the purpose you intend to use a given copy of an experiment.

**Comment by JPLRepo** [comment]
I'll look into it. Probably should be a separate Button as some users might want the existing functionality as well.

**Comment by JPLRepo** [comment]
The best option is to add a second button to fill science into a drive from all sciencecontainers but exclude Labs (ScienceConverter) and command modules with crewcapacity > 0. So Probes are still included.
