### ISSUE TITLE
Sky doesn't magnify properly.

### ISSUE THREAD

**Issue by vladtcvs** [JPLRepo/TarsierSpaceTechnology#66]
Steps to reproduce: direct telescope to the Mun, select scale=10.

Expected result:
Mun and sky image in telescope will be 10 times greater

Actual result:
Mun increases, sky doesn't

**Comment by vladtcvs** [comment]
![image](https://user-images.githubusercontent.com/3390973/65166096-b3c45600-da48-11e9-98df-ff0a9f1abf7c.png)

**Comment by vladtcvs** [comment]
Also, if you rotate telescope a bit, then the image of the Mun will move over the stars. It's completely wrong

**Comment by JPLRepo** [comment]
This is already implemented. There is a game difficulty setting to turn the starfield zoom on and off.
Be prepared though.. it's pretty bad. This is simply because the KSP skybox is not high enough resolution.
![Inked2020-02-08 14_27_37_LI](https://user-images.githubusercontent.com/9981382/74079162-570d1a80-4a7f-11ea-8ed4-68dfc34a6057.jpg)

**Comment by vladtcvs** [comment]
Hello!
Sorry for late answer. Zooming star field works incorrect. When this option is on, star field still zoomed wrong.

Attached screenshots contains Mun photos with the same star marked near the Mun with different zoom. It's easy to see, that when you increase zoom, the star became closer to the Mun edge, and on the last image it is closed by the Mun. But it's completly wrong. It's easy to test with usual camera, that when you zoom, image just became bigger, but object don't hide each other.

![Screenshot at 2020-05-20 14-53-44](https://user-images.githubusercontent.com/3390973/82443505-4a4e8880-9aaa-11ea-8daa-5d04757a337e.png)
![Screenshot at 2020-05-20 14-53-56](https://user-images.githubusercontent.com/3390973/82443501-491d5b80-9aaa-11ea-8181-13d1a3a9b571.png)
![Screenshot at 2020-05-20 14-54-09](https://user-images.githubusercontent.com/3390973/82443509-4ae71f00-9aaa-11ea-9fac-158955b1febb.png)

**Comment by vladtcvs** [comment]
Examples of stars near the Moon from stellarium.

When I zoom, star field zoom in the same scale as the Moon:
![Screenshot at 2020-05-20 15-27-39](https://user-images.githubusercontent.com/3390973/82446023-88e64200-9aae-11ea-8754-56ff600006da.png)
![Screenshot at 2020-05-20 15-27-32](https://user-images.githubusercontent.com/3390973/82446025-8a176f00-9aae-11ea-9575-736b2b74d98e.png)
![Screenshot at 2020-05-20 15-27-20](https://user-images.githubusercontent.com/3390973/82446026-8ab00580-9aae-11ea-821e-012184738a53.png)
