### ISSUE TITLE
KSP 1.9 -- Bodies Not Showing

### ISSUE THREAD

**Issue by AdmiralRadish** [JPLRepo/TarsierSpaceTechnology#69]
Log Included -- There are a TON of errors. I cut probably 120+ Megabytes of errors from this log, all repeating the last 30 or so lines:
[Player.log](https://github.com/JPLRepo/TarsierSpaceTechnology/files/4255530/Player.log)

Save:
[default.zip](https://github.com/JPLRepo/TarsierSpaceTechnology/files/4255460/default.zip)

Tested on a brand new 1.9 save. I reinstalled Kerbal just to verify. Tarsier and MM are the only mods included in this log.

Problem: Launch a Tarsier telescope into a suborbital flight around Kerbin and point it at the moon. As seen in the screenshots, the moon is missing even though it is targeted. Similarly, far bodies like Jool + moons are not displaying either. Targets are still showing up, as is the background.
![MoonMissing](https://user-images.githubusercontent.com/20134826/75341975-7ff52400-5863-11ea-8e42-867eb2749d0a.png)
![MoonSelected](https://user-images.githubusercontent.com/20134826/75341977-808dba80-5863-11ea-9856-a5f4456dfbb4.png)

**Comment by AdmiralRadish** [comment]
Since MiniAVC was throwing megabyte after megabyte of errors, I decided to remove it and see what happened. Although the bodies are still missing, it seems the error count is substantially reduced. Also, clearly there's some "camera copy" error going on here:
[Player.log](https://github.com/JPLRepo/TarsierSpaceTechnology/files/4255638/Player.log)

This error might have something to do with one of these changes to 1.9 (pulled from the changelog) @JPLRepo 

- Added Camera mode (unlocked camera movement controls) when game is paused in flight and you hide the UI.
- Implement single camera system when running in DX11 for improved performance.

**Comment by JPLRepo** [comment]
You are running the mod in KSP 1.9.
The current version of this mod does not support KSP 1.9

**Comment by AdmiralRadish** [comment]
I'm very well aware of that @JPLRepo but, since the new version has been out for 2-ish weeks I thought it might be useful to contribute known issues. It's already been referenced on the forum post so it warrants proper documentation in my mind. Considering this is the public repo space for bugfixing I've included the necessary files here. Cheers mate.

**Comment by JPLRepo** [comment]
Not a bug for the current release, as it does not support the version KSP 1.9.x
But when the mod is updated to support 1.9.x it will of course support the single vs two cameras systems that KSP 1.9.x has depending on the GPU patform (DX11 vs OpenGL).

**Comment by AdmiralRadish** [comment]
@JPLRepo Sounds good, hopefully the info helps with the process! Thanks for keeping up such a great mod, I can't wait for 1.9

**Comment by JPLRepo** [comment]
I was already fully aware of what needed to be done.
You do know I'm lead dev on KSP right? So I'm completely cognizant of everything that changes in the game.
But thanks for taking the time to report the issue with good information. A lot of people don't bother and just complain that their game/mod isn't working.
Version is out already for 1.9.x.

**Comment by AdmiralRadish** [comment]
Actually, it's because you're the lead dev that I was a bit surprised at how quiet it had been around here since the update! With Lisas, Sarbian, and Linus picking up so many mods, I've been seeing a lot of MIA developer threads and I just wanted to make sure you hadn't gotten too swept away in the work/update process and needed somebody looking at a fork.

Keep up the (truly) incredible work, everyone on the team there!

**Comment by JPLRepo** [comment]
I have not abandoned my mods. If I ever found myself in the situation of not wanting to or being able to maintain, update and improve my mods I would announce it on the forum and ask for people to take over. 
In this case, I was going to update my mods for 1.9.0 but had some inside information and a need to produce a 1.9.1 update. Now that that’s out, I intend to update all my mods and have started to today.
Thanks for the feedback as well, appreciate it.
Cheers.

**Comment by AdmiralRadish** [comment]
Insider trading for your own mods Repo? Tsk tsk tsk haha!

Cheers for the mod update, the good info, and for 1.9.1. Quality all around.
