### ISSUE TITLE
Galaxies not appearing. No kopernicus installed.

### ISSUE THREAD

**Issue by Animatical** [JPLRepo/TarsierSpaceTechnology#72]
When I use the deep space telescope, spin it around, and randomly click "research" (with research bodies) Sometimes it will find a galaxy. But then when I go to look at that galaxy, there is nothing there. I don't have kopernicus installed, and when a contract says to take a picture of a galaxy, it makes me point at empty space. I have no idea what is causing this, and I hope eventually this can get fixed.
👍 
[Player.log](https://github.com/JPLRepo/TarsierSpaceTechnology/files/4730626/Player.log)

**Comment by JPLRepo** [comment]
I took a look at your log. And from what I can see. The Galaxies are indeed being loaded in your startup of KSP, there are no errors reported at all in your log.
I loaded up the mod myself with KSP and indeed I can see galaxies.
So there is nothing I can investigate or fix here.
My guess is there is some other mod you have installed that may be causing some kind of conflict (though there is no evidence in the log) as you have many mods installed. I'd suggest trying a vanilla copy/install of KSP and just this mod and see if the galaxies are working for you.
If so, you can slowly install mods until you find the culprit.
