### ISSUE TITLE
Is 1.11 support on its way?

### ISSUE THREAD

**Issue by parpar78** [JPLRepo/TarsierSpaceTechnology#76]
Hey, just a quick question:
will you support 1.11.1 soon?

In 1.11.1 i get an error whenever i "control from here" with a telescope.
"Object reference not set to an instance of an object"

I added player.log as you request.
[Player.log](https://github.com/JPLRepo/TarsierSpaceTechnology/files/5897808/Player.log)
And KSP.log, just in case.
[KSP.log](https://github.com/JPLRepo/TarsierSpaceTechnology/files/5897815/KSP.log)

I know the mod doesn't support 1.11.1 yet, but i thought if you plan on supporting it this info might be useful.

I just wanna end this by saying i love this mod and appreciate the work you do!

Greetings, Parpar78

P.S.: if any more info is required, just ask.

**Comment by JPLRepo** [comment]
I see lots of those errors in your log. but none of them are errors being caused by this mod.
It looks like a bunch of other mods you have installed have errors and problems.
